___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [2]:
import numpy as np 

#### 2. Create an array from my_list=[5,10,15,20,25]

In [3]:
my_list=[5,10,15,20,25]
arr = np.array(my_list)
arr

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array 5x5 zeros 

In [4]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array 4x4 ones assign data type int

In [5]:
np.ones([4,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### 5. Make all the values of the array above 7

In [6]:
np.ones((4,4),dtype='int')*7

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 6. Create same array above with full method

In [7]:
np.full([4,4],7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 

In [8]:
np.arange(2,17,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with values between 0 to 25

In [10]:
np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with values between 0 to 25 using linspace

In [12]:
np.linspace(0,24,25, dtype="int").reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 10. Create 5 random number with numpy

In [15]:
np.random.rand(5)

array([0.43797116, 0.52065633, 0.95428967, 0.13834439, 0.38599308])

#### 11. Create random normal distributed 5x5 array

In [16]:
np.random.randn(25).reshape(5,5)

array([[ 0.8322158 , -0.82110168,  0.84621184, -1.69344733,  0.6477929 ],
       [ 0.60849681, -0.08614562,  0.85207496, -1.35453162, -0.54329329],
       [-0.32209765, -2.23621719,  0.71259679, -1.88763944,  0.17433143],
       [-0.91522278, -0.49303071, -0.67604407,  1.65471256,  2.7749611 ],
       [-0.52357773, -1.43005027,  0.53172713, -0.944696  ,  0.59668141]])

#### 12. Create 3x4 shaped array with random int numbers between 20 and 50 with numpy

In [18]:
np.random.randint(20,50,12).reshape(3,4)

array([[49, 28, 20, 46],
       [34, 43, 21, 49],
       [27, 38, 21, 20]])

#### 13. Reshape the array below with shape 6x8

In [20]:
ranarr = np.array([52, 48, 21, 29, 15, 35,  3, 29, 43, 48, 38,  8, 44,  2, 46, 27, 11, 29, 30, 26,  8, 49, 19,  2,  9, 38, 40, 36, 16, 41, 39, 17, 20, 42, 23, 35, 45, 18, 40,  9, 36, 37,  5, 17, 44, 36,  2, 52])

In [22]:
ranarr.reshape(6,8)

array([[52, 48, 21, 29, 15, 35,  3, 29],
       [43, 48, 38,  8, 44,  2, 46, 27],
       [11, 29, 30, 26,  8, 49, 19,  2],
       [ 9, 38, 40, 36, 16, 41, 39, 17],
       [20, 42, 23, 35, 45, 18, 40,  9],
       [36, 37,  5, 17, 44, 36,  2, 52]])

In [37]:
#reshape with -1
ranarr.reshape(-1,8)

array([[52, 48, 21, 29, 15, 35,  3, 29],
       [43, 48, 38,  8, 44,  2, 46, 27],
       [11, 29, 30, 26,  8, 49, 19,  2],
       [ 9, 38, 40, 36, 16, 41, 39, 17],
       [20, 42, 23, 35, 45, 18, 40,  9],
       [36, 37,  5, 17, 44, 36,  2, 52]])

## Numpy Indexing and Selection


## Create array below
mat= np.arange(1,17).reshape(4,4)
mat

#### 14. Write code that reproduces the output shown below.<br>

In [38]:
mat= np.arange(1,17).reshape(4,4) 
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [39]:
mat[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array.

In [40]:
mat[:,0]

array([ 1,  5,  9, 13])

#### 16. Get the values in 2nd row for every 2 step.

In [41]:
mat[1,::2]

array([5, 7])

#### 17.Assign 77 to every cell in 3rd column.

In [43]:
mat[:,2] = 77

In [44]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 2nd row 1st column, 4th row 2nd column.

In [45]:
mat[[1,3],[0,1]]

array([ 5, 14])

#### 19. Take between 2nd and last row with step 2 and between 1 and last column with step 2.

In [46]:
mat[1::2,::2]

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [77]:
mat[:,2] = 77

In [78]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [79]:
mat[mat<10]

array([1, 2, 4, 5, 6, 8, 9])

In [80]:
mat[mat>12]

array([77, 77, 77, 13, 14, 77, 16])

In [81]:
mat[mat<10]+mat[mat>12]

array([78, 79, 81, 18, 20, 85, 25])

#### 21. Get the standard deviation of the result above

In [82]:
(mat[mat<10]+mat[mat>12]).std()

29.700546274093877

#### 22. Get the sum of second column from array above

In [83]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [88]:
mat[:,2]=[3,7,11,15]

In [89]:
#print array here
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [90]:
mat[:,1].sum(axis=0) 
#sum(mat[:, 1])

32

#### 23. Get the median,mean and std of 3rd row from array above

In [91]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [92]:
mat[2]

array([ 9, 10, 11, 12])

In [93]:
#median
np.median(mat[2])

10.5

In [94]:
#mean
np.mean(mat[2])

10.5

In [95]:
#std
np.std(mat[2])

1.118033988749895

# Pandas Section

In [96]:
import pandas as pd

**Read Salaries.csv take a look at first 5 rows, df info and df statistical measurements**

In [101]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [130]:
salary=pd.read_csv('Salaries.csv')
salary

Id       EmployeeName  ...         Agency  Status
0          1     NATHANIEL FORD  ...  San Francisco     NaN
1          2       GARY JIMENEZ  ...  San Francisco     NaN
2          3     ALBERT PARDINI  ...  San Francisco     NaN
3          4  CHRISTOPHER CHONG  ...  San Francisco     NaN
4          5    PATRICK GARDNER  ...  San Francisco     NaN
...      ...                ...  ...            ...     ...
49725  49726   Crystal DeFrantz  ...  San Francisco     NaN
49726  49727   Antoinette Wells  ...  San Francisco     NaN
49727  49728        Robert Rudy  ...  San Francisco     NaN
49728  49729       Sean Kerrisk  ...  San Francisco     NaN
49729  49730      Rachelle Axel  ...            NaN     NaN

[49730 rows x 13 columns]

In [131]:
salary.head()

Id       EmployeeName  ...         Agency  Status
0   1     NATHANIEL FORD  ...  San Francisco     NaN
1   2       GARY JIMENEZ  ...  San Francisco     NaN
2   3     ALBERT PARDINI  ...  San Francisco     NaN
3   4  CHRISTOPHER CHONG  ...  San Francisco     NaN
4   5    PATRICK GARDNER  ...  San Francisco     NaN

[5 rows x 13 columns]

In [109]:
salary.tail()

Id      EmployeeName  ...         Agency  Status
49725  49726  Crystal DeFrantz  ...  San Francisco     NaN
49726  49727  Antoinette Wells  ...  San Francisco     NaN
49727  49728       Robert Rudy  ...  San Francisco     NaN
49728  49729      Sean Kerrisk  ...  San Francisco     NaN
49729  49730     Rachelle Axel  ...            NaN     NaN

[5 rows x 13 columns]

In [108]:
salary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49730 entries, 0 to 49729
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Id                49730 non-null  int64  
 1   EmployeeName      49730 non-null  object 
 2   JobTitle          49730 non-null  object 
 3   BasePay           49730 non-null  float64
 4   OvertimePay       49729 non-null  float64
 5   OtherPay          49729 non-null  float64
 6   Benefits          13570 non-null  float64
 7   TotalPay          49729 non-null  float64
 8   TotalPayBenefits  49729 non-null  float64
 9   Year              49729 non-null  float64
 10  Notes             0 non-null      float64
 11  Agency            49729 non-null  object 
 12  Status            0 non-null      float64
dtypes: float64(9), int64(1), object(3)
memory usage: 4.9+ MB


In [116]:
salary

Id       EmployeeName  ...         Agency  Status
0          1     NATHANIEL FORD  ...  San Francisco     NaN
1          2       GARY JIMENEZ  ...  San Francisco     NaN
2          3     ALBERT PARDINI  ...  San Francisco     NaN
3          4  CHRISTOPHER CHONG  ...  San Francisco     NaN
4          5    PATRICK GARDNER  ...  San Francisco     NaN
...      ...                ...  ...            ...     ...
49725  49726   Crystal DeFrantz  ...  San Francisco     NaN
49726  49727   Antoinette Wells  ...  San Francisco     NaN
49727  49728        Robert Rudy  ...  San Francisco     NaN
49728  49729       Sean Kerrisk  ...  San Francisco     NaN
49729  49730      Rachelle Axel  ...            NaN     NaN

[49730 rows x 13 columns]

In [110]:
salary.describe()

Id        BasePay    OvertimePay  ...          Year  Notes  Status
count  49730.00000   49730.000000   49729.000000  ...  49729.000000    0.0     0.0
mean   24865.50000   75598.465810    6231.691032  ...   2011.272879    NaN     NaN
std    14355.95878   42293.132137   12801.333149  ...      0.445444    NaN     NaN
min        1.00000       0.000000       0.000000  ...   2011.000000    NaN     NaN
25%    12433.25000   48472.430000       0.000000  ...   2011.000000    NaN     NaN
50%    24865.50000   77251.210000     102.380000  ...   2011.000000    NaN     NaN
75%    37297.75000  105934.660000    6673.030000  ...   2012.000000    NaN     NaN
max    49730.00000  302578.000000  245131.880000  ...   2012.000000    NaN     NaN

[8 rows x 10 columns]

**How many different year value are there**

In [132]:
salary.Year.value_counts()

2011.0    36159
2012.0    13570
Name: Year, dtype: int64

**Print out max and avg Totalpay**

In [133]:
#max
salary.TotalPay.max()

567595.43

In [118]:
#avg
salary.TotalPay.mean()

86440.16133363078

**How many records are there which have TotalPay bigger than avg TotalPay**

In [125]:
len(salary.TotalPay[salary.TotalPay > salary.TotalPay.mean()].value_counts())


23979

In [121]:
len(salary["TotalPay"][salary.TotalPay > salary.TotalPay.mean()].value_counts())

23979

**How much does ALBERT PARDINI make (including benefits)?**

In [127]:
salary["TotalPay"][salary["EmployeeName"]=="ALBERT PARDINI"]

2    335279.91
Name: TotalPay, dtype: float64

**Who is lowest paid person**

In [129]:
salary[salary.TotalPayBenefits==salary.TotalPayBenefits.min()]['EmployeeName']

36156        PAULETTE ADAMS
36157         KAUKAB MOHSIN
36158    JOSEPHINE MCCREARY
Name: EmployeeName, dtype: object

**What are the unique Jobs in dataset?**

In [134]:
salary.JobTitle.unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'IS Operator-Senior',
       'Public Health Team Leader', 'Vet Laboratory Technologist'],
      dtype=object)

**List 3 least common Jobs**

In [135]:
salary["JobTitle"].value_counts().tail(3)

BARBER                            1
Employee Relations Representat    1
IS TECHNICIAN - ASSISTANT         1
Name: JobTitle, dtype: int64

**How many people earned more than avg in 2012**

In [139]:
salary[(salary.TotalPayBenefits>salary.TotalPayBenefits.mean()) & (salary.Year==2012)]['EmployeeName'].count()

13570

**How many people have the word Manager in their job title?**

In [140]:
def manager_func(x):
    if 'manager' in x.lower():
        return True
    else:
        return False

In [141]:
len(salary[salary.JobTitle.apply(lambda x:manager_func(x))])

1880

In [142]:
#use apply function here
len(salary[salary.JobTitle.apply(lambda x: True if 'manager' in x.lower() else False)])

1880

**Take Id,EmployeeName,JobTitle,TotalPay and TotalPayBenefits columns with iloc and assign it as sal_new dataframe**

In [143]:
sal_new=salary.iloc[:,[0,1,2,7,8]]
sal_new.head()

Id       EmployeeName  ...   TotalPay  TotalPayBenefits
0   1     NATHANIEL FORD  ...  567595.43         567595.43
1   2       GARY JIMENEZ  ...  538909.28         538909.28
2   3     ALBERT PARDINI  ...  335279.91         335279.91
3   4  CHRISTOPHER CHONG  ...  332343.61         332343.61
4   5    PATRICK GARDNER  ...  326373.19         326373.19

[5 rows x 5 columns]

In [144]:
sal_new

Id       EmployeeName  ...   TotalPay  TotalPayBenefits
0          1     NATHANIEL FORD  ...  567595.43         567595.43
1          2       GARY JIMENEZ  ...  538909.28         538909.28
2          3     ALBERT PARDINI  ...  335279.91         335279.91
3          4  CHRISTOPHER CHONG  ...  332343.61         332343.61
4          5    PATRICK GARDNER  ...  326373.19         326373.19
...      ...                ...  ...        ...               ...
49725  49726   Crystal DeFrantz  ...   84710.49         120372.37
49726  49727   Antoinette Wells  ...   81985.60         120354.27
49727  49728        Robert Rudy  ...   96334.25         120354.07
49728  49729       Sean Kerrisk  ...   84641.31         120351.98
49729  49730      Rachelle Axel  ...        NaN               NaN

[49730 rows x 5 columns]

**Take columns betweeen EmployeeName and TotalPayBenefits with loc and assign it o sal_new df**
 

In [145]:
sal_new=sal_new.loc[:,'EmployeeName':'TotalPayBenefits']
sal_new

EmployeeName  ... TotalPayBenefits
0         NATHANIEL FORD  ...        567595.43
1           GARY JIMENEZ  ...        538909.28
2         ALBERT PARDINI  ...        335279.91
3      CHRISTOPHER CHONG  ...        332343.61
4        PATRICK GARDNER  ...        326373.19
...                  ...  ...              ...
49725   Crystal DeFrantz  ...        120372.37
49726   Antoinette Wells  ...        120354.27
49727        Robert Rudy  ...        120354.07
49728       Sean Kerrisk  ...        120351.98
49729      Rachelle Axel  ...              NaN

[49730 rows x 4 columns]

**Print out the names of the employees who earn more than min, but less than avg**

In [146]:
salary[(salary.TotalPayBenefits>salary.TotalPayBenefits.min()) & 
       (salary.TotalPayBenefits<salary.TotalPayBenefits.mean())]['EmployeeName']

9955           WAYNE HOM
9956        WILLIE PRYOR
9957        ASHA JAMESON
9958     EUGENE FLANNERY
9959          SAMUEL XIE
              ...       
36151        MARVA MOORE
36152    MARCELLA TUCKER
36153      ROCK CRAWFORD
36154      SERENA HUGHES
36155       JOE BROWN JR
Name: EmployeeName, Length: 26201, dtype: object